### ISSUE TITLE
Ch 5 - Adversarial Search visualisation links broken

### ISSUE THREAD

**Issue by ptah23** [aimacode/aima-javascript#78]
The Javascript links on http://aimacode.github.io/aima-javascript/5-Adversarial-Search/ is broken

**Comment by Ghost---Shadow** [comment]
It has been broken for quite a while. Nothing new. It will be fixed when someone works on this chapter.

**Comment by redblobgames** [comment]
The links are to {,c_}`alphabeta.js` but the files are {,c_}`alphaBeta.js`, so they work for local testing if you're on a case insensitive file system but they don't work on the production site. Chapter 5 hasn't been implemented yet so I think whoever implements them will fix this (maybe @ishapotnis1).

**Comment by Rishav159** [comment]
Looks like this issue is now fixed and can be closed.

**Comment by redblobgames** [comment]
It works fine on a case insensitive file system but is still broken on case insensitive systems. I think it'll be fixed when someone replaces this chapter.

**Comment by Rishav159** [comment]
You mean 'still broken on case *sensitive systems'

**Comment by redblobgames** [comment]
Er, yes, that's what I mean :)

**Comment by newbazz** [comment]
I would like to work on this issue.

**Comment by redblobgames** [comment]
@newbazz go for it

**Comment by newbazz** [comment]
Can someone help me out how to solve the issue.

**Comment by redblobgames** [comment]
@newbazz If you don't know how to solve this issue then leave it for whoever is working on chapter 5. Thanks.

**Comment by newbazz** [comment]
Yeah m ready to leave. Can you help me to figure it out which issues are for beginners?

**Comment by redblobgames** [comment]
@newbazz Let's take this discussion to gitter

**Comment by ayanb07** [comment]
@redblobgames I think this bug is no longer valid. @regalhotpocket had changed the name as linked. So this bug is a closed bug I think.

**Comment by redblobgames** [comment]
@ayanb07 Ahh you are correct.
